// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyPortfolioProject.DAL.Context;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyPortfolioProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250713124046_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("e6e21232-145c-44a1-ade1-9db6646f39c3"),
                            RoleId = new Guid("9f4a2dba-20ca-481c-af32-70df2c57b256")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.About", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Details = "Merhaba, ben Emir Baycan. Uzun süredir web ve mobil yazılım geliştirme alanında çalışıyorum. Full-stack web development, yapay zeka, mikroservis mimarisi ve otomasyon üzerine birçok projede yer aldım. Kendi projelerimle girişimcilik yolunda ilerliyorum. Python, C#, JavaScript, React, Angular, Node.js, Docker ve bulut servislerinde tecrübem var. Hedefim; teknolojiyle hayatı kolaylaştıran, sürdürülebilir ve ölçeklenebilir sistemler kurmak. Araştırmaya, öğrenmeye ve üretmeye devam ediyorum.",
                            SubDescription = "Yazılım Geliştirici, Girişimci, Teknoloji Tutkunu",
                            Title = "Ben Kimim"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.AppRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f4a2dba-20ca-481c-af32-70df2c57b256"),
                            ConcurrencyStamp = "937c22d4-04ba-4805-855f-cc0f140403d2",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e6e21232-145c-44a1-ade1-9db6646f39c3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0b8ba39f-0b26-446b-a8d8-c697071a870b",
                            Email = "emir-baycan@hotmail.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Emir",
                            NormalizedEmail = "EMIR-BAYCAN@HOTMAIL.COM",
                            NormalizedUserName = "EMIR",
                            PasswordHash = "AQAAAAEAACcQAAAAEPERPqsSTPJZx08iM7qt3UNR7RE6GSdyxIf358XvvW7GPNp3dk0mlw94jLu06MRgGQ==",
                            PhoneNumber = "549 615 4243",
                            PhoneNumberConfirmed = true,
                            SecurityStamp = "8e035b2e-6d1b-49d2-9d7f-9df836da2a33",
                            Surname = "Baycan",
                            TwoFactorEnabled = false,
                            UserName = "emir"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Antalya, Türkiye",
                            Description = "Her türlü iş birliği, proje teklifi veya danışmanlık için bana ulaşabilirsiniz. Hızlıca dönüş yaparım.",
                            Email = "emir-baycan@hotmail.com",
                            Phone = "549 615 4243",
                            Title = "Bana Ulaşın"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Experience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Head")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = "Eylül 2024 - Kasım 2024",
                            Description = "Kurumsal web projelerinin analiz, geliştirme ve entegrasyon süreçlerinde tam sorumluluk üstlendim.",
                            Head = "Karalar Kağıt",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 2,
                            Date = "Ocak 2024 - Hala çalışıyorum",
                            Description = "Dijital altyapı ve otomasyon projelerinin planlama, geliştirme ve bakımından sorumluyum.",
                            Head = "My Partners Hukuk Bürosu",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 3,
                            Date = "Ekim 2022 - Aralık 2022",
                            Description = "Web ve e-ticaret platformlarının tasarım, geliştirme ve uygulama süreçlerini yönettim.",
                            Head = "Eyüp Sultan Tulumbacısı",
                            Title = "Web Programcısı"
                        },
                        new
                        {
                            Id = 4,
                            Date = "Mart 2022 - Ağustos 2023",
                            Description = "Eğitim platformunun kullanıcı ve sınav modüllerinin analiz, geliştirme ve uygulama aşamalarında sorumluluk aldım.",
                            Head = "Hukuki Yeterlilik Akademisi",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 5,
                            Date = "Şubat 2022 - Nisan 2022",
                            Description = "Danışan takip sistemi ve online randevu altyapısının geliştirme süreçlerinde görev aldım.",
                            Head = "Terapi Kliniği",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 6,
                            Date = "Temmuz 2021 - Eylül 2021",
                            Description = "Doküman yönetim sistemi ve online danışmanlık modüllerinin yazılım süreçlerinde aktif rol oynadım.",
                            Head = "Morkoç Hukuk Bürosu",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 7,
                            Date = "Şubat 2021 - Şubat 2023",
                            Description = "Yazılım geliştirme, ekip yönetimi ve iş geliştirme süreçlerinin tamamında sorumluluk üstlendim.",
                            Head = "Kalenux",
                            Title = "CEO"
                        },
                        new
                        {
                            Id = 8,
                            Date = "Eylül 2020 - Kasım 2020",
                            Description = "Kurumsal web sitesi ve müşteri iletişim sistemlerinin analiz ve geliştirme aşamalarında görev aldım.",
                            Head = "Karalar Prefabrik",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 9,
                            Date = "Ocak 2020 - Ocak 2021",
                            Description = "Eğitim programları için web tabanlı yazılım çözümlerinin geliştirme süreçlerinde görev aldım.",
                            Head = "Hukuk Eğitim Programları",
                            Title = "Web Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 10,
                            Date = "Ocak 2019 - Ocak 2023",
                            Description = "Oyun tabanlı platformun yazılım altyapısının geliştirilmesi ve otomasyon süreçlerinde sorumluluk aldım.",
                            Head = "Do Eloboost",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 11,
                            Date = "Ocak 2019 - Nisan 2019",
                            Description = "Web tabanlı yazılım ve otomasyon sistemlerinin geliştirilmesinde görev aldım.",
                            Head = "Murat Bulat Hukuk Bürosu",
                            Title = "Yazılım Uzmanı"
                        },
                        new
                        {
                            Id = 12,
                            Date = "Ocak 2018 - Ocak 2019",
                            Description = "Derneğe özel dijital projelerin planlama ve geliştirilme süreçlerinde aktif görev üstlendim.",
                            Head = "Girişimci Hukukçular Derneği",
                            Title = "Yazılım Uzmanı"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Feature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Projelerinde çözüm odaklı yaklaşım, yeni teknolojilere hızlı adaptasyon ve girişimcilik tutkusu ile hareket eden bir yazılımcı.",
                            ImageId = new Guid("22f2b3e5-f705-4313-b05e-23d0b1decfca"),
                            Title = "Yenilikçi ve Üretken"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Images");

                    b.HasData(
                        new
                        {
                            Id = new Guid("22f2b3e5-f705-4313-b05e-23d0b1decfca"),
                            FileName = "hero-bg.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("7aaa428e-0fc4-439e-98b5-c58edd0ee662"),
                            FileName = "kalenuxer/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("854b0ed3-ed70-4577-ba90-be5e978b52a3"),
                            FileName = "myp/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("66b9bc58-966a-412e-8b8a-863f04752316"),
                            FileName = "hya/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("58289eab-8396-48c8-ae1d-b479cb48ee85"),
                            FileName = "morkoc/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("46ba78d1-daa6-4336-9467-8d3b063c3488"),
                            FileName = "kp/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("afe4d6bf-e4a6-4b72-b5dd-361e12330ca2"),
                            FileName = "est/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("b01f9534-6ed3-4472-906b-6aff11b90e52"),
                            FileName = "ghd/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("85e0f94d-3977-418b-952f-0a4e57dae5fc"),
                            FileName = "hep/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("d44718e9-ff96-4fc0-b4b6-ad6f3be741eb"),
                            FileName = "de/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("3f7dc8d1-9f3f-43ed-b6d1-46d91899815d"),
                            FileName = "tk/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("51f4b123-09e3-46f8-a7dd-db67ed99eb5d"),
                            FileName = "mb/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("48935904-b8ec-456f-8a54-9f6379fee302"),
                            FileName = "lamp/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("f60c82a7-637a-466c-b322-0fd8b3ee05ce"),
                            FileName = "mern/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("bbb8e201-90cc-4e63-814a-fd09a8d179b5"),
                            FileName = "nmlr/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("65c3b076-11ed-46a7-9f89-1929edfc40fa"),
                            FileName = "next/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("5fbf64aa-6129-46fd-8440-8008bea09cfb"),
                            FileName = "ac/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("85357de3-76b1-4919-b70a-7b64a664e5fc"),
                            FileName = "v/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("122570d1-3a21-48a7-b6cf-5c42a9e7fd6b"),
                            FileName = "shc/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("f3c9d194-f455-4dd6-a1a9-afd65457f523"),
                            FileName = "dsd/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("9f15d95f-8d03-457b-b59f-7211e268af82"),
                            FileName = "dsr/1.webp",
                            FileType = "image/webp"
                        },
                        new
                        {
                            Id = new Guid("c5d157af-beac-4f3e-a7be-a3446a6ba436"),
                            FileName = "dsa/1.webp",
                            FileType = "image/webp"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("MessageDetail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Portfolio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uuid");

                    b.Property<string>("SubTitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ImageId");

                    b.ToTable("Portfolios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Maksimum performans ve esneklik için geliştirilmiş yeni nesil bir web uygulama çatısıdır. Kalenuxer; çoklu dil desteği, ileri düzey küçültme ve karmaşıklaştırma, sunucu tarafı render (SSR), modüler şablonlama (mail, bölüm, sayfa), sınıflandırma, SVG’den ikona dönüştürme, versiyon kontrolü, optimize CSS/JS yapısı ve güçlü yerelleştirme gibi özelliklerle, ölçeklenebilir ve üretime hazır uygulamaların hızlı geliştirilmesini sağlar.",
                            ImageId = new Guid("7aaa428e-0fc4-439e-98b5-c58edd0ee662"),
                            SubTitle = "Yeni nesil web uygulama çatısı",
                            Title = "Kalenuxer",
                            Url = "https://github.com/emirbaycan/Kalenuxer"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Kalenuxer’in SSR algoritmalarını kullanarak, dinamik SQL verilerini optimize HTML yapılarına sorunsuzca dönüştüren; gerçek zamanlı içerik güncellemeleri, güvenli müşteri yönetimi ve hukuk ofislerine özel güçlü bir kontrol paneli içeren özel bir web sitesi.",
                            ImageId = new Guid("854b0ed3-ed70-4577-ba90-be5e978b52a3"),
                            SubTitle = "Dinamik hukuk sitesi",
                            Title = "My Partners Hukuk Bürosu",
                            Url = "https://myp.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kalenuxer ile geliştirilmiş, eğitim firmalarına özel kapsamlı web sitesi ve yönetim paneli. Güvenli ders yönetimi, çok seviyeli kullanıcı erişimi ve gerçek zamanlı güncelleme özellikleriyle ölçeklenebilir ve kolay içerik yönetimi sağlar.",
                            ImageId = new Guid("66b9bc58-966a-412e-8b8a-863f04752316"),
                            SubTitle = "Eğitim yönetim paneli",
                            Title = "Hukuki Yeterlilik Akademisi",
                            Url = "https://hya.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kalenuxer tabanlı, hız ve güvenlik odaklı, hukuk sektörüne özel dinamik içerik yönetimi ve dava yönetimi sağlayan web sitesi ve özel kontrol paneli.",
                            ImageId = new Guid("58289eab-8396-48c8-ae1d-b479cb48ee85"),
                            SubTitle = "Hız ve güvenlik odaklı hukuk sitesi",
                            Title = "Morkoç Hukuk Bürosu",
                            Url = "https://lawnux.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kalenuxer tabanlı, prefabrik konut firmalarına yönelik gelişmiş katalog yönetimi, müşteri etkileşimi ve güçlü arka plan yetenekleriyle tam kapsamlı web sitesi ve yönetim paneli.",
                            ImageId = new Guid("46ba78d1-daa6-4336-9467-8d3b063c3488"),
                            SubTitle = "Prefabrik konut katalog yönetimi",
                            Title = "Karalar Prefabrik",
                            Url = "https://kp.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Kalenuxer ile geliştirilen, popüler bir tatlı markası için kullanıcı odaklı ve yüksek dönüşüm sağlayan ürün sergileme ve yönetimi kolay modern bir web sitesi.",
                            ImageId = new Guid("afe4d6bf-e4a6-4b72-b5dd-361e12330ca2"),
                            SubTitle = "Ürün sergileme ve yönetimi",
                            Title = "Eyüp Sultan Tulumbacısı",
                            Url = "https://eyp.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 7,
                            Description = "LAMP stack ile geliştirilmiş, üye yönetimi, etkinlik otomasyonu ve güvenli iletişim modülleri içeren, bir hukuk derneğine özel ilk web platformu ve yönetim sistemi.",
                            ImageId = new Guid("b01f9534-6ed3-4472-906b-6aff11b90e52"),
                            SubTitle = "Dernek üye yönetimi sistemi",
                            Title = "Girişimci Hukukçular Derneği",
                            Url = "https://ghd.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Kalenuxer altyapısıyla geliştirilen, sürekli yeni özelliklerle güncellenen ve çoklu kurs içerik desteği sunan eğitim topluluğu web sitesi ve kontrol paneli.",
                            ImageId = new Guid("85e0f94d-3977-418b-952f-0a4e57dae5fc"),
                            SubTitle = "Çoklu kurs içerik desteği",
                            Title = "Hukuk Eğitim Programları",
                            Url = "https://hep.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Kalenuxer ile geliştirilen, otomasyon, performans ve güvenlik açısından optimize edilmiş bir online oyun servisi sitesi ve yönetim paneli.",
                            ImageId = new Guid("d44718e9-ff96-4fc0-b4b6-ad6f3be741eb"),
                            SubTitle = "Oyun servisi yönetim paneli",
                            Title = "Do Eloboost",
                            Url = "https://de.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Laravel ve özel JavaScript kütüphaneleriyle kodlanmış, psikologlara yönelik dinamik web sitesi ve kontrol paneli. Laravel’i standart hosting ortamında çalışacak şekilde optimize ettim.",
                            ImageId = new Guid("3f7dc8d1-9f3f-43ed-b6d1-46d91899815d"),
                            SubTitle = "Psikologlara özel dinamik web sitesi",
                            Title = "Terapi Kliniği",
                            Url = ""
                        },
                        new
                        {
                            Id = 11,
                            Description = "LAMP stack üzerinde geliştirilmiş, otomatik dosya yönetimi, güvenli müşteri portalı ve pratik yönetim araçları sunan kapsamlı bir hukuk bürosu web sitesi.",
                            ImageId = new Guid("51f4b123-09e3-46f8-a7dd-db67ed99eb5d"),
                            SubTitle = "Otomatik dosya yönetimi, müşteri portalı",
                            Title = "Murat Bulat Hukuk Bürosu",
                            Url = ""
                        },
                        new
                        {
                            Id = 12,
                            Description = "Kalenuxer ve LAMP altyapısıyla geliştirilen çok dilli portfolyo siteleri. Tam yığın (full-stack) uzmanlığımı ve ölçeklenebilir mimari yaklaşımımı gösteren projeler.",
                            ImageId = new Guid("48935904-b8ec-456f-8a54-9f6379fee302"),
                            SubTitle = "Çok dilli portfolyo sitesi",
                            Title = "LAMP ile Portfolio",
                            Url = "https://lamp.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 13,
                            Description = "React, Node.js ve MySQL üzerinde Ubuntu/Apache ile çalışan çok dilli portfolyo siteleri. Gelişmiş arayüz teknikleri ve arka uç entegrasyonu ile öne çıkıyor.",
                            ImageId = new Guid("f60c82a7-637a-466c-b322-0fd8b3ee05ce"),
                            SubTitle = "React, Node.js tabanlı dinamik portfolyo",
                            Title = "React ile Portfolio",
                            Url = "https://mern.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Laravel, React, Node.js ve Three.js ile tam yığın, interaktif portfolyo siteleri. Modern UI/UX ve güçlü teknik demo niteliğinde.",
                            ImageId = new Guid("bbb8e201-90cc-4e63-814a-fd09a8d179b5"),
                            SubTitle = "Modern UI/UX interaktif site",
                            Title = "Laravel ve React ile Portfolyo",
                            Url = "https://nmlr.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Next.js tabanlı çok dilli portfolyo siteleri. Dinamik içerik, Resend ile e-posta entegrasyonu ve bulut tabanlı ölçeklenebilirlik özellikleri.",
                            ImageId = new Guid("65c3b076-11ed-46a7-9f89-1929edfc40fa"),
                            SubTitle = "Next.js tabanlı çok dilli site",
                            Title = "Next ile Portfolio",
                            Url = "https://next.emirbaycan.com.tr"
                        },
                        new
                        {
                            Id = 16,
                            Description = "C#, Selenium, Geckofx ve bulut servisleri (AWS, Google Cloud, Azure) kullanarak geliştirdiğim otomatik hesap oluşturucu. Yüksek hacimli ve tam otomatik kayıt işlemleri için VPN/proxy desteği de mevcut.",
                            ImageId = new Guid("5fbf64aa-6129-46fd-8440-8008bea09cfb"),
                            SubTitle = "Otomatik hesap oluşturucu (C# & Selenium)",
                            Title = "Hesap Oluşturucu",
                            Url = ""
                        },
                        new
                        {
                            Id = 17,
                            Description = "Python, Selenium ve Tor Browser IP döngüsüyle, ölçeklenebilir ve anonimleştirilmiş insan verisi üretici. Gerçekçi kullanıcı simülasyonu sağlar.",
                            ImageId = new Guid("85357de3-76b1-4919-b70a-7b64a664e5fc"),
                            SubTitle = "Anonimleştirilmiş insan verisi üretici",
                            Title = "Oylayıcı",
                            Url = ""
                        },
                        new
                        {
                            Id = 18,
                            Description = "Verilen parametrelerle nesne yüksekliğini hassas şekilde hesaplayan Python algoritması. Matematiksel modelleme ve algoritma geliştirme yeteneğini gösterir.",
                            ImageId = new Guid("122570d1-3a21-48a7-b6cf-5c42a9e7fd6b"),
                            SubTitle = "Nesne yüksekliği hesaplama",
                            Title = "Hız ve Uzunluk Hesaplayıcı",
                            Url = ""
                        },
                        new
                        {
                            Id = 19,
                            Description = "Python ve YOLO kullanarak, canlı kamera akışlarından dijital ekranları gerçek zamanlı tespit eden bilgisayarla görü uygulaması.",
                            ImageId = new Guid("f3c9d194-f455-4dd6-a1a9-afd65457f523"),
                            SubTitle = "Python & YOLO tabanlı ekran tespit",
                            Title = "Dijital Ekran Bulucu",
                            Url = "https://github.com/emirbaycan/yolo_digital_screen_detector"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Canlı video akışlarında dijital ekranların otomatik tespiti ve OCR ile okuması. Python ile bilgisayarla görü ve karakter tanıma teknolojilerini bir araya getirir.",
                            ImageId = new Guid("9f15d95f-8d03-457b-b59f-7211e268af82"),
                            SubTitle = "Gerçek zamanlı dijital ekran OCR",
                            Title = "Dijital Ekran Okuyucu",
                            Url = "https://github.com/emirbaycan/ocr_digital_screen_reader"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Gerçek zamanlı dijital ekran izleme, eşik değer aşıldığında otomatik görüntü kaydı ve uyarı sistemi.",
                            ImageId = new Guid("c5d157af-beac-4f3e-a7be-a3446a6ba436"),
                            SubTitle = "Gerçek zamanlı izleme ve uyarı",
                            Title = "Dijital Ekran Alarmı",
                            Url = "https://github.com/emirbaycan/digital_screen_alarm_with_rtsp_camera"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Title = "Backend",
                            Value = 100
                        },
                        new
                        {
                            Id = 2,
                            Title = "Frontend",
                            Value = 100
                        },
                        new
                        {
                            Id = 3,
                            Title = "Full-stack Geliştirme",
                            Value = 100
                        },
                        new
                        {
                            Id = 4,
                            Title = "Serverside",
                            Value = 100
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.SocialMedia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SocialMedias");
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("NameSurname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Emir ile birlikte hukuk büromuzun dijital altyapısını tamamen modernize ettik. Dinamik kontrol paneli ve müşteri yönetimi konusunda beklentimizin çok üstünde çözümler sundu.",
                            NameSurname = "Av. Murat Kara",
                            Title = "My Partners Hukuk Bürosu | Kurucu Avukat"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Web platformumuzu sıfırdan tasarlayıp tüm üyelik ve etkinlik süreçlerini dijitalleştirdi. Hızlı teslimat ve teknik destek açısından eşsiz bir iş ortağı.",
                            NameSurname = "Murat Kara",
                            Title = "Girişimci Hukukçular Derneği | Kurucu"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Kurumsal sitemizi ve katalog yönetim sistemimizi kurduktan sonra müşteri geri dönüşlerimizde %40 artış yaşadık. Yazılım kalitesi ve iş takibi gerçekten çok iyi.",
                            ImageUrl = "hasan-karalar.webp",
                            NameSurname = "Burak Kara",
                            Title = "Karalar Prefabrik | Kurucu"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Geliştirdiği özel panel ve otomasyonlar sayesinde eğitim süreçlerimiz çok daha verimli hale geldi. Teknik bilgisinin yanı sıra iletişimde de çok profesyonel.",
                            NameSurname = "Muhammet Morkoç",
                            Title = "Hukuki Yeterlilik Akademisi | Kurucu"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Özellikle dava ve dosya yönetim sistemimizdeki yenilikçi yaklaşımı sayesinde işlerimizi daha hızlı ve güvenli yürütebiliyoruz. Tavsiye ederim.",
                            NameSurname = "Muhammet Morkoç",
                            Title = "Morkoç Hukuk | Avukat"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Farklı projelerimizde Emir Baycan ile çalışma fırsatım oldu. Her seferinde sonuca odaklı, hızlı ve ölçeklenebilir projeler teslim etti.",
                            NameSurname = "Uğur",
                            Title = "Freelance İşveren"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Teknolojideki yenilikleri takip eden, algoritmik zekası ve analiz gücüyle öne çıkan bir yazılımcı. Takım çalışmalarında ve proje yönetiminde çok güçlü.",
                            NameSurname = "Berke",
                            Title = "Full-Stack Developer | Takım Arkadaşı"
                        });
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.ToDoList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Status")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ToDoLists");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.AppRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyPortfolioProject.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.AppUser", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.Image", "Image")
                        .WithMany("AppUsers")
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Feature", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.Image", "Image")
                        .WithMany("Features")
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Portfolio", b =>
                {
                    b.HasOne("MyPortfolioProject.DAL.Entities.Image", "Image")
                        .WithMany("Portfolios")
                        .HasForeignKey("ImageId");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("MyPortfolioProject.DAL.Entities.Image", b =>
                {
                    b.Navigation("AppUsers");

                    b.Navigation("Features");

                    b.Navigation("Portfolios");
                });
#pragma warning restore 612, 618
        }
    }
}
